name: ci

on:
  push:
    paths:
      - "**.c"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"

jobs:

  unix:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4

    - run: cmake --workflow --preset default

  windows_msvc:
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4

    - run: cmake --workflow --preset msvc
